### ISSUE TITLE
Certain tables/variables drop with data.table error for DC only

### ISSUE THREAD

**Issue by sheffe** [GL-Li/totalcensus#1]
Ran into an odd issue today. I'm working with all states and a number of tables within the ACS5. For a small subset of these tables, and only for DC, data.table exits with the following error:

> Class attributes at column 81 of input list at position 2 does not match with column 81 of input list at position 1. Coercion of objects of class 'factor' alone is handled internally by rbind/rbindlist at the moment.

Variables that fail include: "B19049_001" "B19301_001" "B19001_001" "B19101_001" (along with other vars from those tables). Those variables *do* work for all 50 other states, and all other variables I tried *do* work for DC, so it doesn't seem to be a problem of missing tables or missing DC data in general.

It takes a long time to run the full set I was working with, so the following example is chunked down to just B01001_001 (works everywhere) and the problem tables, and to just VT and DC.

sf_read_acs5year <- safely(read_acs5year)
test_vars <- c( "B01001_001", "B19049_001", "B19301_001", "B19001_001", "B19101_001")

dc_test <- test_vars %>%
  map(.f = ~sf_read_acs5year(year = 2016, 
                             states = c("VT", "DC"), 
                             table_contents = .x,
                             summary_level = "tract"))

I'm running the latest CRAN version of totalcensus and data.table, and can send more if we need to get further into the weeds.

I'm enjoying your package, and it's already saving me lots of time!

**Comment by GL-Li** [comment]
I checked the original downloaded data of "B19301_001" for DC. The problem is that a couple of missing values are filled with dot ".". Normally a missing value is just a blank "". With the dot, the whole column is read into character instead of numbers and is unable to rbind with a numeric column. Give me some time to fix it. Thank you for finding the bug.

**Comment by sheffe** [comment]
Thank you for getting to the root of that. I am going to implement a local workaround this morning that will add the `.` to na.strings in the fread() calls, but I don't know how effectively that will generalize to all of the raw files. If it's helpful and you think that solution will generalize, I can post the code here or submit a PR.

**Comment by sheffe** [comment]
@GL-Li quick update. I tried the na.strings solution in fread but experienced the same errors. It also looks like the '.' for NAs exists in many files, some of which *do* work just fine using read_acs5year. I've attached a CSV with filepaths for 3 test states, MA VT and DC and counts of the character sequence `,.,` in the file -- plenty of instances across working and nonworking states/tables.

[na_dot_counts.txt](https://github.com/GL-Li/totalcensus/files/1763916/na_dot_counts.txt)

states <- c("ma", "vt", "dc")

files <- map(states, ~ list.files("/Volumes/DataExt/census_data/acs5year/2016/group2",
                                  full.names = TRUE, pattern = .x)) %>%
  unlist()

check_contents <- function(f){
  contents <- read_lines(f)
  dot_na <- grepl(pattern = "\\,\\.\\,", x = contents)
  sum(dot_na)
}

na_dot_counts <- tibble(file = files,
                        na_dots = map_int(files, check_contents)) %>%
  filter(na_dots > 0)

write_csv(na_dot_counts, "na_dot_counts.csv")

**Comment by GL-Li** [comment]
@sheffe Please install the github version. I have tested for all test_vars and it works fine. Please let me know your test result. Thanks.

**Comment by sheffe** [comment]
@GL-Li works fine! I tested on a large superset of the ACS vars mentioned above and all good. Thanks for the fast fix. And please let me know if I can be useful in testing anything else out.

**Comment by GL-Li** [comment]
@sheffe You're very welcome to post any issue and request here.
