### ISSUE TITLE
set_path_to_census temporary

### ISSUE THREAD

**Issue by neverfox** [GL-Li/totalcensus#11]
It seems that at some point the behavior of set_path_to_census changed to use tempdir instead of the provided path. Is that intentional? It made some sense to me to set an explicit path but not have it become permanent across R sessions (e.g. a project-specific path), but now it seems the only options are a permanent, cross-session path or a truly temporary directory.

**Comment by GL-Li** [comment]
It is not intentional. Could you provide more details under which it happened? So far the idea is to save all summary files in one location and all projects read data from that location. Please explain a little bit about the use case of  "set an explicit path". Thanks.

**Comment by neverfox** [comment]
I'm referring to https://github.com/GL-Li/totalcensus/blob/0a61ab6e36d3d2bd5b3e7ee39845d8e8d0a4d031/R/set_path_to_census.R#L70 which used to be:
```
Sys.setenv(PATH_TO_CENSUS = path)
```

So now, rather than storing the files in the path passed into the function when you choose temporary, it stores the files in whatever location `tempdir()` returns, making it transient and unpredictable. `path` only gets used if the user selects permanent. Meaning the semantics have changed from 'temporary' meaning "temporarily set the path to `path`" to 'temporary' meaning "actually use a temporary directory and ignore the provided path".

**Comment by GL-Li** [comment]
The `tempdir()` randomly assign a directory for that session. It disappears when the session is closed. It is not very useful but I have to follow the rules of CRAN. If I understand correctly, you want to save downloaded data for a project under the directory of the same projects. In this case, you can specify a path with `set_path_to_cencus("path-to-this-project")` for each project. I may need to change the word "permanent" to "local" so that it has less confusion.

**Comment by neverfox** [comment]
Yes but if you choose permanent, you're not just setting that path for the project, you're setting it for all sessions because it alters the user's .Renviron file. In other words, I can see there being three theoretical possibilities here:

1. Use a temp directory (using `tempdir`)
2. Use a specified directory that is good for the current session only (`Sys.setenv(PATH_TO_CENSUS = path)`) 
3. Use a specified directory that is good for this and all future sessions (alter .Renviron).

As of the latest commit 1f538d445e2d21c2a279b63418c0c403fa2736ca, the package only allows for (1) and (3). Prior to that commit, it supported (2) and (3). So my question was essentially why (2) was dropped in favor of (1)? You mentioned the "rules of CRAN" but I'm not sure why CRAN would dictate that change.

I could see all three being useful options to offer the user when they run `set_path_to_census` but (2) and (3) are arguably more useful more of the time given the time investment required to download the data.

**Comment by GL-Li** [comment]
I can see the problem if you are running multiple sessions simultaneously. Otherwise, you can always change the path in .Renviron file in the current session with `set_path_to_census()`.
