### ISSUE TITLE
Is it possible to add census data from 1990

### ISSUE THREAD

**Issue by memeticist** [GL-Li/totalcensus#12]
Thank you for creating this.

The data from the 1990 census appears to be in a DOS format, is there any way to incorporate it into your package?

https://www2.census.gov/census_1990/

Thank You

**Comment by GL-Li** [comment]
It will be too time-consuming to include the 1990 decennial data. There is even no electronic version of the technical documentation of the summary file 1. I need to copy and paste a lot of data from the documentation to the package.

**Comment by memeticist** [comment]
No problem, I assumed as much. I am bewildered that the wealthiest nation on earth has failed to make more of an effort to maintain its own records. It is not as though 1990 was the dark ages, it had its charms.

Thanks
