### ISSUE TITLE
Error in eval(lhs, parent, parent) : object 'acs_Data' not found

### ISSUE THREAD

**Issue by cesposo** [GL-Li/totalcensus#15]
While attempting to execute code, process hangs @ about Alabama header file 49. Also, system resources are heavily taxed for just the one state, approx. 38 gigs on Ubuntu vanilla.

**Comment by mtc2013** [comment]
This is when running code like this:

vars_dec = search_tablecontents("dec", years=2010)$reference
dec_data <- read_decennial(
    year = 2010,
    table_contents = vars_dec,
    states = "AL",
    summary_level = "block group"
  )

**Comment by GL-Li** [comment]
This could be a memory leak problem with data.table. To make it work, you may want to read 1000 table_contents each time and then combine all columns to get the final results.
