### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by aycankatitas** [GL-Li/totalcensus#16]
Hello, 

Thank you for creating this package, it is very useful! 

I'm getting frequent errors when I'm downloading ACS1 yearly files for all states which prevents me from efficiently using the package. I'm downloading data for 2005-2016. My 2005 files downloaded fine, but starting from 2006 some states kept giving errors. Downloading 2008 almost all states are giving errors. 

I'm able to continue downloading after trying to run the code two-three times manually. 

Updated package, restarted R etc, nothing worked. It happens both in CRAN and development version. 

Here's the error message I'm getting. I get this sometimes at the download stage and sometimes at the unzipping stage. 

trying URL 'https://www2.census.gov/programs-surveys/acs/summary_file/2008/data/1_year/SouthDakota/all_sd.zip'
Error in download.file(url, save_as, method = "auto") : 
  cannot open URL 'https://www2.census.gov/programs-surveys/acs/summary_file/2008/data/1_year/SouthDakota/all_sd.zip'
In addition: Warning message:
In download.file(url, save_as, method = "auto") :
  cannot open URL 'https://www2.census.gov/programs-surveys/acs/summary_file/2008/data/1_year/SouthDakota/all_sd.zip': HTTP status was '500 Internal Server Error'

Would appreciate if you could help me with this.

**Comment by GL-Li** [comment]
I tried ```aaa = read_acs1year(year = 2008, state = "SD")``` and it worked well. From the error message you have, the server that stores the census data had some problems when you were downloading the data. Please try again and let me know if you still have the problem.

**Comment by aycankatitas** [comment]
Yes I think it was the census server error, because some years I was able to collect fine but some years gave errors. But I think there is nothing you can do to fix it on your end. I’m done collecting the data now, thank you for your help! 
--
Aycan Katitas
PhD Candidate, International Relations
Woodrow Wilson Department of Politics
University of Virginia
