### ISSUE TITLE
reading table "B01003_001" yields data.table error for duplicate colname

### ISSUE THREAD

**Issue by sheffe** [GL-Li/totalcensus#2]
Small issue here: using read_acs5year to read the population variable B01003_001 results in a data.table error for duplicate colnames, as in the following:

read_acs5year(year = 2016,
              states = "MA",
              table_contents = "B01003_001",
              summary_level = "tract")

Error in setnames(., table_contents, paste0(table_contents, "_", est_marg)) : 
  Some duplicates exist in 'old': B01003_001

If I'm reading correctly, read_acs5year is pulling that variable already and (later) renames it `population` to accompany other table_contents items; it's a duplicate colname if included directly in the vector of variables.

**Comment by GL-Li** [comment]
Yes you are right. I guess I forgot to fix this problem for read_acsXyear.

**Comment by GL-Li** [comment]
fixed.
