### ISSUE TITLE
Update for 2021 ACS5 release?

### ISSUE THREAD

**Issue by sheffe** [GL-Li/totalcensus#23]
Hi -- the [2021 ACS5 was just released](https://www.census.gov/programs-surveys/acs/news/data-releases.html). Is there an existing plan to update the package, or would a user PR be helpful? Any pointers/suggestions for the usual update process would be welcome.

**Comment by RealCoChenchao** [comment]
I would agree with John. Please let me know how I can be helpful as well.

**Comment by GL-Li** [comment]
Working on the update. Should be done soon.

**Comment by GL-Li** [comment]
Please install the development version and let me know of any issues.  The package size exceeds the CRAN limit. Hopefully, I can trim it down and submit it to CRAN during the holiday break. Thanks.

**Comment by sheffe** [comment]
@GL-Li thank you! Just did a test run and everything's looking pretty smooth for the 2021 update. Really appreciate the quick action here.
