### ISSUE TITLE
Error in get_geoheaders_of_summarylevel(summary_level) 

### ISSUE THREAD

**Issue by jianxiapyh** [GL-Li/totalcensus#24]
Hi I am attempting to read block level race data from the 2000 & 2010 decennial census. The code below works fine for year 2010. However, when I change the year to 2000
```R
{
  race = read_decennial(
    year = 2000,
    states = 'IL',
    table_contents = c(
      "total_population = P0010001", # All Residents
    ),
    summary_level = "block"
  )
}
```
This returns an error of 
```R
Error in get_geoheaders_of_summarylevel(summary_level) : 
  object 'geoheaders' not found
```
I am not sure what went wrong. Any assistance would be greatly appreciated!

Thank you

**Comment by jianxiapyh** [comment]
After some digging, I found in R/utilities.R's switch_summarylevel function
it change's  block_code to 101 when it is in year 2000 (line 555). However, in get_geoheaders_of_summarylevel(), I don't see the if else statement for summary_level == '101'.

**Comment by GL-Li** [comment]
Fixed the bug. Please install from github `devtools::install_github("GL-Li/totalcensus")` and try again. Thanks.

**Comment by jianxiapyh** [comment]
Thank you! the bug is fixed!
