### ISSUE TITLE
rbindlist failing for DC ACS 5-year tract estimates

### ISSUE THREAD

**Issue by emallickhossain** [GL-Li/totalcensus#3]
When reading in the ACS 5-year median income tract estimates for DC, it throws an error that rbindlist() is failing because of mismatched column types. The error is 
`Error in rbindlist(list(dt1, dt2)) : 
  Class attributes at column 195 of input list at position 2 does not match with column 195 of input list at position 1. Coercion of objects of class 'factor' alone is handled internally by rbind/rbindlist at the moment.`

The following code should reproduce the error:
`read_acs5year(year = 2016, states = i, table_contents = "B19013_001", summary_level = "tract")`

My guess is that this is probably due to the fact that for median income in DC, tract 2.01 has a median income of "-", so data.table could be coercing this to a character and trying to bind it with an integer or numeric. This doesn't happen for my spot check of median age, so it's probably just because there's not a numeric value in this space.

Hopefully this is a quick fix!

**Comment by GL-Li** [comment]
Sorry for the late reply. I tried the following code and it works fine. What is "i" in your example?

`DC <- read_acs5year(
             year = 2016, 
              states = "DC", 
              table_contents = "B19013_001", 
              summary_level = "tract"
)`

**Comment by emallickhossain** [comment]
Strange. I just tried it again and it's still throwing an error. I had been using `i` to loop over all states, but just DC is giving me the following:

```
library(totalcensus)
DC <- read_acs5year( year = 2016, states = "DC", table_contents = "B19013_001", summary_level = "tract" )

Reading DC 2016 ACS 5-year survey geography file
Error in rbindlist(list(dt1, dt2)) : 
  Class attributes at column 195 of input list at position 2 does not match with column 195 of input list at position 1. Coercion of objects of class 'factor' alone is handled internally by rbind/rbindlist at the moment.
```

**Comment by GL-Li** [comment]
If you are using the installation from CRAN, there might be some problem. Please install the development version from github.

**Comment by emallickhossain** [comment]
Will do! That worked!
