### ISSUE TITLE
PCT12I table contents don't exist

### ISSUE THREAD

**Issue by xiaojiemao** [GL-Li/totalcensus#4]
Hi, it seems that all variables in PCT12I in 2010 NY decennial dataset (table contents PCT012I001 - PCT012I209) don't exist in the search_tablecontents. As a result, the read_decennial() doesn't work for this table. In search_tablecontents, all PCT12I variables are wrongly taken as PCT12H variables (PCT12H appears twice in the search_tablecontents). Would you mind fixing this? Thanks!

**Comment by GL-Li** [comment]
Please re-install this development version and try again. Thanks.
