### ISSUE TITLE
Adding more years of data

### ISSUE THREAD

**Issue by chrowe** [GL-Li/totalcensus#5]
How easy is it to add another survey year? e.g.
`lookup_acs5year_2010`
`lookup_acs1year_2016`

**Comment by GL-Li** [comment]
It is relatively easy to add data after 2011, as census bureau published Sequence_Number_and_Table_Number_Lookup table for recent years. The package already includes 2016 data. I am adding newly published 2017 acs1year data.

**Comment by chrowe** [comment]
Thanks for the update!

Sorry, I meant the 2010 acs1year data.

We are trying to compare tract level changes over time on a national scale so your approach of downoalding all the files will work great for us but older data is important. 

What would it take to do older data?

**Comment by GL-Li** [comment]
Find tables for 2010 but the format is different. Should be able to process the 2010 1-year and 5-year data this weekend.

**Comment by chrowe** [comment]
That's great to hear. I am happy to help in any way I can. It would be nice to know how to add our own in the future. Maybe your upcoming commits will help illustrate that.

**Comment by GL-Li** [comment]
Please check out the latest commit. 

Following the steps to add your own data. I made a lot of changes and have no time to check for each detail.  I have added and tested 2008 and 2010 acs data. There might be problems with other years. Please submit pull requests and contribute to the package after you successfully add new data.

Step 1: Download Sequence Number/Table Number Lookup file, text format.  
- For years after 2011, download from https://goo.gl/WyrsuY.
- For earlier years, go to https://goo.gl/aQ96oy and select the year → documentation → select 1_year or 5_year → user_tools. The file may be named as merge_5_6.txt.
- Save the file to totalcensus/data_raw/ and rename it, for example  2015 acs 1 year, as ACS_1yr_Seq_Table_Number_Lookup_2015.txt.  

Step 2: Download Appendices file if available.
- The file is avaiable after 2013, download from https://goo.gl/WyrsuY. 
Save the file to totalcensus/data_raw and rename it, for example, for 2015 acs 1 year, as ACS_2015_SF_1YR_Appendices.xls, 

Step 3: Generate lookup table dataset. 
- In totalcensus/data_raw/ subdirectory find create_acs_file_table_lookup.R. Add a line of code like lookup_acs5year_2010 <- make_acs_lookup(5, 2010) and run it. A .RData file will be added into totalcensus/data/. After this step, the new data will be usable. You can rebuild the package and use the data. 
- In totalcensus/R/ find data_acs.R and add documentation for the new dataset following format in the file.

Step 4: add the new data for search_tableconent()
- In totalcensus/R/ find file search_census_and_acs.R then function generate_acs_tablecontents(), 

Step 5: check the newly added data
- In totalcensus/test/ find file test_data_consistency_over_years.R. The file plots a few variables over years. The numbers differ too much over years, there might be something wrong.

**Comment by chrowe** [comment]
Thanks, This is great!!

I will give it a try today and let you know how it goes.

**Comment by chrowe** [comment]
The acs5year_2010 data you added seems to be working as expected. Thanks!
At this point that is all we need but I expect we will want more shortly so I will let you know how it goes when we add that and contribute back.

**Comment by GL-Li** [comment]
Now the package includes more ACS data. Please check them out

- ACS 1 year: 2005 - 2017
- ACS 5 year: 2009 - 2016
