### ISSUE TITLE
Perhaps README should note installation for for Microsoft version of R is slightly different

### ISSUE THREAD

**Issue by AronT-TLV** [GL-Li/totalcensus#7]
When I do a search in the CRAN/MRAN search engines I see the package there, but when I try to install on version 3.4.0 and 3.4.3 I get the following error message (with the appropriate version):

```
Warning in install.packages :
  package ‘totalcensus’ is not available (for R version 3.4.3)
```
Because it's Microsoft R the actually installation command must be:

```
install.packages("totalcensus", dependencies=TRUE, repos='http://cran.rstudio.com/')
```

Perhaps this should be noted in the README.

**Comment by GL-Li** [comment]
I have no experience with Microsoft R. Could you modify the READM.Rmd (not README.md) file to add installation for Microsoft R and submit a pull request? Also is there any difference to install the github version in Microsoft R?

**Comment by AronT-TLV** [comment]
I’ll test the Github version and then submit a PR.
